name: Playwright Tests
on: push

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: yarn playwright install --with-deps
      - name: Build app
        run: yarn build
      - name: Run Playwright
        run: yarn playwright test
        env:
          HOME: /root
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results
          retention-days: 30
  chromatic:
    name: Run Chromatic on Playwright tests
    needs: playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      - name: Download Playwright test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          playwright: true
          projectToken: ${{ secrets.CHROMATIC_PW_PROJECT_TOKEN }}
